name: Package Extension
on:
  workflow_call:
    inputs:
      command:
        description: "Full or Pre?"
        required: true
        default: "vsce package --target web"
        type: string
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: package with vsce
        run: |
          npm install -g @vscode/vsce --omit=dev
          ${{ inputs.command }}
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.1
        with:
          name: Extension Package
          path: ./*.vsix
