name: Package Extension
on:
  workflow_call:
    inputs:
      command:
        description: "Full or Pre?"
        required: true
        default: "vsce package --target web"
        type: string
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout repository
      - name: import Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Check version
        uses: actions/github-script@v6
        with:
          script: |
            const runChecks = require(".actions/checks.js");
            runChecks();
      - name: Commit Changes
        continue-on-error: true
        run: |
          git pull
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "post runChecks"
          git push
      - name: package with vsce
        run: |
          npm install -g @vscode/vsce
          ${{ inputs.command }}
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.1
        with:
          name: Extension Package
          path: ./*.vsix
